[package]
name = "tower-server"
description = "tower single-binary server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "tower"
path = "src/main.rs"

[dependencies]
tower-core = { workspace = true }
tower-driver = { workspace = true }
axum = { workspace = true }

tokio = { workspace = true }
clap = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
ulid = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
futures = { workspace = true }
directories = { workspace = true }
toml = { workspace = true }
async-trait = { workspace = true }
tower = { version = "0.5.3", features = ["util"] }
tower-service = "0.3.3"
hyper-util = "0.1.21"
hyper = { version = "1.11.1", features = ["http1"] }
http = "1.5.0"

[lints]
workspace = true

[dev-dependencies]
tempdir = "0.3.7"
