[package]
name = "tower-client"
description = "tower CLI client library"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tower-core = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
ulid = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
